[package]
name = "cratex"
version = "0.2.0"
edition = "2021"
description = "execute crates directly"
license = "MIT"


[dependencies]
beautify = "0.2.0"
indicatif = "0.17.9"
num_cpus = "1.16.0"
tempfile = "3.15.0"

[[bin]]
name = "cratex"
path = "src/main.rs"
